version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: swat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./gen_ssl.sh:/gen_ssl.sh:ro
      - ./certs/:/certs:Z
      - ./my.cnf:/etc/mysql/my.cnf:ro
      - ./initdb:/docker-entrypoint-initdb.d/:ro
